name: Go Build and Docker Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19'

    - name: Build Go Project
      run: go build -v -o ledokol

    - name: Test
      run: go test -v ./...

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ledokol
        path: .
      
  build-image:
    needs: build-go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        path: output
    - name: Build the Docker image
      run: docker build . -f docker/Dockerfile --tag kirphone/ledokol:$(date +%s)
